name: Publish packages to PPA repository

on: [ workflow_dispatch ]

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create PPA repo
        run: ./.github/scripts/publish_packages.sh
        shell: bash
        env:
          GPG_PRIVATE_KEY: ${{ secrets.PPA_GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.PPA_GPG_PASSPHRASE }}
          GITHUB_USERNAME: net-stalker
          EMAIL: dmytro.shcherbatiuk@netstalker.io

      - name: Uploading packages to PPA
        run: |
          sudo apt-get install -y dput
          dput ppa:dshcherbatiuk/netstalker .