name: Publish Debian packages to PPA repository

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag'
        required: true
        default: 'latest'
      file:
        description: 'The file name of the distribution'
        required: true
        default: netmonitor_0.1.0_amd64.deb
      repo:
        description: 'The repository name'
        required: true
        default: monitor

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update platform
        run: sudo apt-get update && sudo apt-get install curl jq

      - name: Download Monitor Release
        run: |
          ./.github/scripts/gh-dl-release.sh
          echo "::info::Commit and push deb package to GitHub"
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add -A .
          git status
          git commit -m "add deb package"
          git push -u origin main
        shell: bash
        env:
          TOKEN: ${{ secrets.PERSONAL_TOKEN_ACCESS_REPO }}
          REPO: net-stalker/${{ github.event.inputs.repo }}
          FILE: ${{ github.event.inputs.file }}
          VERSION: ${{ github.event.inputs.tag }}

      - name: Create Debian PPA repo
        run: |
          ./.github/scripts/create_debian_ppa_repo.sh
          echo "::info::Commit and push to GitHub"
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add -A
          git commit -m "add debian ppa repo"
          git push -u origin main
        shell: bash
        env:
          GPG_PRIVATE_KEY: ${{ secrets.PPA_GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.PPA_GPG_PASSPHRASE }}
          GITHUB_USERNAME: net-stalker
          EMAIL: dmytro.shcherbatiuk@netstalker.io